language: ruby
rvm:
- 2.0.0
script: bundle exec jekyll build

notifications:
  email:
    recipients:
      - free-software@remibarbe.fr
    on_success: never
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#remiii"
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
    on_success: always
    on_failure: always
