#Github page settings
lsi: false
highlighter: pygments

destination: ./_site

#url: http://localhost:10090
#url: http://remiii.github.com
url: https://remibarbe.fr

author:
    name: Rémi Barbe
    github: remiii
    twitter: Remiii_

production_url: https://remibarbe.fr

permalink: /blog/:year/:month/:day/:title
relative_permalinks: no

api:
    me:
        name: "Remi Barbe"
        email: "-"
        age: "30"
        gender: "male"
        city: "Paris"
        hometown: "Paris"
        photo: "https://remibarbe.fr/assets/images/remi-barbe-thumb-v001.jpg"
        favorite-foods:
            - "big mac"
            - "mac delux"
            - "whopper"
        favorite-drinks:
            - "coca cola"
            - "apple jus"

