source: ./src
destination: ./site

safe: true

#url: http://localhost:10090
url: http://www.remibarbe.fr

author:
    name: Rémi Barbe
    email: contact@remibarbe.fr
    github: remiii
    twitter: Remiii_


production_url: http://remibarbe.github.com

permalink: /blog/:year/:month/:day/:title

